-- Script Povoamento da Base de Dados

-- Gerentes
INSERT INTO Gerente (email, password) VALUES ('chuck@restaurante.pt', 'chuck');
INSERT INTO Gerente (email, password) VALUES ('ronaldo@restaurante.pt', 'ronaldo');
INSERT INTO Gerente (email, password) VALUES ('alcides@restaurante.pt', 'alcides');

-- Fornecedores
INSERT INTO Fornecedor (email, contacto, idGerente, nome) VALUES ('xpto@fornecedor.pt', 123456789, 1,'XPTO');
INSERT INTO Fornecedor (email, contacto, idGerente, nome) VALUES ('cobertura@fornecedor.pt', 987654321, 1,'Cobertura, lda');
INSERT INTO Fornecedor (email, contacto, idGerente, nome) VALUES ('aiaiai@fornecedor.pt', 111222333, 1,'AIAIAI');
INSERT INTO Fornecedor (email, contacto, idGerente, nome) VALUES ('uiuiui@fornecedor.pt', 444555666, 1,'UIUIUI');
INSERT INTO Fornecedor (email, contacto, idGerente, nome) VALUES ('abcde@fornecedor.pt', 777888999, 1,'ABCDE, lda');

-- Horários
INSERT INTO Horario (Nome) VALUES ('Turno Almoço');
INSERT INTO Horario (Nome) VALUES ('Turno Jantar');

-- DataHora
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-02 07:30:00',1,'2020-06-02 11:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-02 11:30:00',1,'2020-06-02 16:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-03 07:30:00',1,'2020-06-03 11:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-03 11:30:00',1,'2020-06-03 16:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-04 07:30:00',1,'2020-06-04 11:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-04 11:30:00',1,'2020-06-04 16:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-05 07:30:00',1,'2020-06-05 11:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-05 11:30:00',1,'2020-06-05 16:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-06 07:30:00',1,'2020-06-06 11:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-06 11:30:00',1,'2020-06-06 16:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-07 07:30:00',1,'2020-06-07 11:00:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-07 11:30:00',1,'2020-06-07 16:00:00');

INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-02 16:00:00',2,'2020-06-02 18:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-02 19:00:00',2,'2020-06-03 00:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-03 16:00:00',2,'2020-06-03 18:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-03 19:00:00',2,'2020-06-04 00:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-04 16:00:00',2,'2020-06-04 18:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-04 19:00:00',2,'2020-06-05 00:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-05 16:00:00',2,'2020-06-05 18:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-05 19:00:00',2,'2020-06-06 00:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-06 16:00:00',2,'2020-06-06 18:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-06 19:00:00',2,'2020-06-07 00:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-07 16:00:00',2,'2020-06-07 18:30:00');
INSERT INTO Datahora (inicio, idHorario, fim) VALUES ('2020-06-07 19:00:00',2,'2020-06-08 00:30:00');

-- Funcionários
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('vinicius@restaurante.pt', 'uelele', '1965-10-21', 'Rua de Cima, nº23', 'Vinícius Leitão', 'Cozinheiro', 1, 1);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('juliana@restaurante.pt', 'uelele', '1995-10-21', 'Rua de Cima, nº33', 'Juliana Gama', 'Emp. Mesa', 1, 2);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('alice@restaurante.pt', 'uelele', '1995-10-21', 'Rua de Cima, nº43', 'Alice Gama', 'Emp. Mesa', 1, 2);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('emilio@restaurante.pt', 'uelele', '1975-11-21', 'Rua de Cima, nº53', 'Emilio Torres', 'Cozinheiro', 1, 1);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('gervasio@restaurante.pt', 'uelele', '1985-10-01', 'Rua de Cima, nº63', 'Gervásio Fidalgo', 'Emp. Balcão', 1, 3);

INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('enzo@restaurante.pt', 'uelele', '1955-10-10', 'Rua de Cima, nº73', 'Enzo Nunes', 'Cozinheiro', 2, 1);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('sara@restaurante.pt', 'uelele', '1997-10-21', 'Rua de Cima, nº83', 'Sara Freitas', 'Emp. Mesa', 2, 2);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('clemente@restaurante.pt', 'uelele', '1999-10-21', 'Rua de Cima, nº93', 'Clemente Azevedo', 'Emp. Mesa', 2, 2);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('rafaela@restaurante.pt', 'uelele', '1998-10-21', 'Rua de Cima, nº103', 'Rafaela Coelho', 'Emp. Mesa', 2, 2);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('roberto@restaurante.pt', 'uelele', '1905-11-21', 'Rua de Cima, nº113', 'Roberto Agostinho', 'Cozinheiro', 2, 1);
INSERT INTO Funcionario (email, password, dataNascimento, morada, nome, cargo, idHorario, idGerente) VALUES ('hugo@restaurante.pt', 'uelele', '1994-10-01', 'Rua de Cima, nº123', 'Hugo Águas', 'Emp. Balcão', 2, 3);

-- Mesas
INSERT INTO Mesa (ocupacao, reservada) VALUES (2, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (2, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (2, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (2, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (4, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (4, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (4, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (4, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (6, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (6, 0);
INSERT INTO Mesa (ocupacao, reservada) VALUES (8, 0);

-- Reservas
INSERT INTO Reserva (dataHora, nomeCliente, nifCliente, idGerente) VALUES ('2020-06-05 13:00:00', 'Raimundo Monteiro', '111000111', 1);
INSERT INTO Reserva (dataHora, nomeCliente, nifCliente, idGerente) VALUES ('2020-06-05 20:30:00', 'S.C. Braga', '000000000', 1);
INSERT INTO Reserva (dataHora, nomeCliente, nifCliente, idGerente) VALUES ('2020-06-06 20:15:00', 'Mafalda Faria', '999000111', 1);
INSERT INTO Reserva (dataHora, nomeCliente, nifCliente, idGerente) VALUES ('2020-06-06 20:00:00', 'Judite Rosa', '999000000', 2);
INSERT INTO Reserva (dataHora, nomeCliente, nifCliente, idGerente) VALUES ('2020-06-06 20:00:00', 'Igor Seabra', '999333000', 2);

-- Artigos
INSERT INTO Artigo (Nome, Preco) VALUES ('Água 1l', 1.2);
INSERT INTO Artigo (Nome, Preco) VALUES ('Água 33cl', 0.7);
INSERT INTO Artigo (Nome, Preco) VALUES ('Refrigerante 33cl', 1.7);
INSERT INTO Artigo (Nome, Preco) VALUES ('Refrigerante 1l', 2.5);
INSERT INTO Artigo (Nome, Preco) VALUES ('Cerveja 33cl', 1.7);
INSERT INTO Artigo (Nome, Preco) VALUES ('Água c/ Gás 33cl', 1.2);
INSERT INTO Artigo (Nome, Preco) VALUES ('Vinho Verde 0.75L', 3.8);
INSERT INTO Artigo (Nome, Preco) VALUES ('Salada Individual', 3.8);
INSERT INTO Artigo (Nome, Preco) VALUES ('Pão de Alho', 1.0);
INSERT INTO Artigo (Nome, Preco) VALUES ('Bifinhos c/ Cogumelos', 5.99);
INSERT INTO Artigo (Nome, Preco) VALUES ('Pescada Assada', 7.99);
INSERT INTO Artigo (Nome, Preco) VALUES ('Lasanha', 6.99);
INSERT INTO Artigo (Nome, Preco) VALUES ('Lasanha Vegetariana', 6.99);
INSERT INTO Artigo (Nome, Preco) VALUES ('Carne de Porco à Alentejana', 8.5);
INSERT INTO Artigo (Nome, Preco) VALUES ('Massa à Lavrador', 8.4);
INSERT INTO Artigo (Nome, Preco) VALUES ('Rojões', 7.5);
INSERT INTO Artigo (Nome, Preco) VALUES ('Bacalhau c/ Broa', 9.8);
INSERT INTO Artigo (Nome, Preco) VALUES ('Café', 0.7);
INSERT INTO Artigo (Nome, Preco) VALUES ('Tiramisú', 1.2);
INSERT INTO Artigo (Nome, Preco) VALUES ('Pudim', 1.3);
INSERT INTO Artigo (Nome, Preco) VALUES ('Arroz Doce', 1.1);

-- Mercadorias
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Água 1l', 'Vitolis', 20, '', 5, '6*1l');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Água 33cl', 'Vitolis', 5, '', 2, '12*33cl');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Refrigerante 33cl', '7-Down', 10, '', 5, '12*33cl');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Refrigerante 1l', '7-Down', 10, '', 5, '6*1l');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Cerveja 33cl', 'Sogres', 10, '', 5, '24*33cl');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Água c/ Gás 33cl', 'Rochas Salgadas', 5, '', 2, '12*33cl');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Vinho Verde 0.75L', 'Vinho Bom', 5, '', 2, '6*0.75L');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Alface', 'Campo', 5, '', 3, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Tomate', 'Campo', 2, '', 3, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Cebola', 'Campo', 7, '', 10, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Azeite', 'Galinha', 15, '', 10, 'l');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Sal', 'Salgado', 12, '', 10, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Pão de Alho', 'Congelados', 12, '', 10, '2 UN');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Coração de Alcatara', 'Vaca Magra', 7, '', 5, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Cogumelos', 'Floresta', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Arroz', 'Asiático', 20, '', 15, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Batata', 'Campo', 21, '', 20, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Natas', 'Agrus', 4, '', 3, '1l');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Pescada', 'Marítimo', 4, '', 5, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Massa Lasanha', 'Gorilla', 4, '', 3, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Carne Picada', 'Vaca Magra', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Béchamel', 'Agrus', 3, '', 1, '1l');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Queijo Ralado', 'Agrus', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Courgette', 'Campo', 3, '', 3, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Beringela', 'Campo', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Alho Francês', 'Campo', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Pá de Porco', 'Vaca Magra', 3, '', 4, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Picles', 'Campo', 2, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Azeitonas', 'Campo', 1, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Salsa', 'Campo', 1, '', 0, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Massa', 'Gorilla', 7, '', 5, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Couve Coração', 'Campo', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Frango', 'Campo', 7, '', 5, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Vitela', 'Vaca Magra', 4, '', 3, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Perna Porco', 'Vaca Magra', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Sange Cozido', 'Vaca Magra', 1, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Bacalhau Posta', 'Rio Manso', 10, '', 7, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Broa', 'Padeiro', 3, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Alho', 'Campo', 0, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Grelos', 'Campo', 2, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Café Grão', 'Mescafé', 6, '', 5, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Biscoito', 'Padeiro', 1, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Mascarpone', 'Agrus', 1, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Mascarpone', 'Agrus', 1, '', 1, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Ovos', 'Campo', 30, '', 24, 'UN');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Leite', 'Agrus', 6, '', 6, 'lt');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Açúcar', 'Padeiro', 2, '', 2, 'kg');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Caramelo', 'Padeiro', 2, '', 2, 'lt');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Gema Ovo', 'Agrus', 2, '', 2, 'lt');
INSERT INTO Mercadoria (Nome, Marca, Stock, Observacoes, quantidadeMinima, embalagem) VALUES ('Canela', 'Padeiro', 0, '', 1, 'kg');

-- MercadoriaInArtigo
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 1, 1);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 2, 2);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 3, 3);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 4, 4);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 5, 5);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 6, 6);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 7, 7);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 8, 8);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 13, 9);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 16, 21);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 50, 21);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 47, 21);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 49, 21);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 46, 21);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 16, 10);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 15, 10);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 14, 10);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 18, 10);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 17, 10);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 37, 17);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 11, 17);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 38, 17);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 40, 17);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 17, 17);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 17, 14);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 30, 14);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 29, 14);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 20, 12);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 22, 12);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 21, 12);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 9, 12);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 12, 12);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 23, 12);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 20, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 22, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 25, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 24, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 23, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 12, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 9, 13);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 31, 15);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 32, 15);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 33, 15);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 27, 15);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 12, 15);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 19, 11);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 11, 11);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 17, 11);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 9, 11);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 47, 20);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 48, 20);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 46, 20);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 45, 20);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 35, 16);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 39, 11);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 39, 17);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 39, 16);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 17, 16);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 28, 16);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 36, 16);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 29, 16);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 27, 14);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 28, 14);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 9, 8);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 12, 8);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 11, 8);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 10, 8);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 47, 19);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 43, 19);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 45, 19);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 42, 19);
INSERT INTO Mercadoriainartigo (idMercadoria, idArtigo) VALUES ( 41, 19);


-- Pedidos
-- 2020-06-02 - Almoço
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 12:23:00', 1, 'Pago', 2, 1);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 12:49:00', 2, 'Pago', 3, 2);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 13:01:00', 3, 'Pago', 2, 3);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 13:05:00', 4, 'Pago', 2, 4);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 13:10:00', 5, 'Pago', 2, 6);
-- 2020-06-02 - Jantar
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 19:53:00', 6, 'Pago', 7, 1);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 20:01:00', 7, 'Pago', 8, 2);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 20:05:00', 8, 'Pago', 9, 5);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-02 20:34:00', 9, 'Pago', 8, 6);
-- 2020-06-03 - Almoço
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 12:23:00', 1, 'Pago', 2, 1);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 12:49:00', 2, 'Pago', 3, 2);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 13:01:00', 3, 'Pago', 2, 3);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 13:05:00', 4, 'Pago', 2, 4);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 13:10:00', 5, 'Pago', 2, 6);
-- 2020-06-03 - Jantar
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 19:53:00', 6, 'Pago', 7, 1);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 20:01:00', 7, 'Pago', 8, 2);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 20:05:00', 8, 'Pago', 9, 5);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-03 20:34:00', 9, 'Pago', 8, 6);
-- 2020-06-04 - Almoço
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 12:23:00', 1, 'Pago', 2, 1);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 12:49:00', 2, 'Pago', 3, 2);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 13:01:00', 3, 'Pago', 2, 3);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 13:05:00', 4, 'Pago', 2, 4);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 13:10:00', 5, 'Pago', 2, 6);
-- 2020-06-04 - Jantar
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 19:53:00', 6, 'Pago', 7, 1);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 20:01:00', 7, 'Pago', 8, 2);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 20:05:00', 8, 'Pago', 9, 5);
INSERT INTO Pedido (dataHora, numero, estado, idFuncionario, mesa) VALUES ('2020-06-04 20:34:00', 9, 'Pago', 8, 6);

-- ArtigoInPedido
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (1, 18, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (1, 6, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (1, 17, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (1, 21, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (2, 2, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (2, 10, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (2, 11, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (2, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (2, 8, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (3, 5, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (3, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (4, 1, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (4, 13, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (4, 18, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (4, 19, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 2, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 7, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 15, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 16, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 19, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (5, 18, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (7, 14, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (7, 5, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (6, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (6, 5, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (6, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (8, 18, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (8, 21, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (8, 19, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (8, 15, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (8, 11, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (8, 7, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (9, 5, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (9, 9, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (9, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (9, 12, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (9, 18, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (9, 19, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (10, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (10, 5, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (10, 10, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (10, 17, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (11, 21, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (11, 2, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (11, 15, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (12, 1, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (12, 8, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (12, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (13, 2, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (13, 10, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (13, 18, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (27, 17, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (27, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (27, 7, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (27, 18, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (27, 19, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (27, 20, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (26, 6, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (26, 18, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (26, 10, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (26, 13, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (26, 11, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (25, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (25, 15, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (25, 11, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (25, 6, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (25, 5, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (24, 17, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (24, 18, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (24, 4, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (23, 18, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (23, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (23, 15, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (23, 4, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (22, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (22, 4, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (22, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (21, 8, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (21, 14, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (21, 16, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (21, 4, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (21, 19, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (14, 4, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (14, 10, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (14, 17, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (14, 18, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (14, 19, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (14, 9, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (20, 6, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (20, 13, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (19, 5, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (19, 16, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (19, 13, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (19, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (18, 10, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (18, 4, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (18, 17, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (18, 18, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (18, 19, 4);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (17, 18, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (17, 17, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (17, 10, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (17, 4, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (17, 19, 3);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (15, 18, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (15, 11, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (15, 6, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (16, 18, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (16, 5, 2);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (16, 14, 1);
INSERT INTO Artigoinpedido (idPedido, idArtigo, quantidade) VALUES (16, 12, 1);